// SET PAGE CONTENT
export const SET_PRODUCT_ITEMS = 'SET_PRODUCT_ITEMS';
export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM';
export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";

// SET SHOPPING CART
export const CART_ITEM_ADD = 'CART_ITEM_ADD';
export const CART_ITEM_REMOVE = 'CART_ITEM_REMOVE';

// SET LOGIN 
export const BEGIN_LOGIN_REQUEST = 'BEGIN_LOGIN_REQUEST';
export const SUCCESS_LOGIN_REQUEST = 'SUCCES_LOGIN_REQUEST';
export const FAIL_LOGIN_REQUEST = 'FAIL_LOGIN_REQUEST';
export const REMEMBER_LOGIN = 'REMEMBER_LOGIN';

// SET REGISTER
export const BEGIN_REGISTER_REQUEST = 'BEGIN_REGISTER_REQUEST';
export const FAIL_REGISTER_REQUEST = 'FAIL_REGISTER_REQUEST';
export const SUCCESS_REGISTER_REQUEST = 'SUCCESS_REGISTER_REQUEST';

// SET UPDATE USERINFO
export const BEGIN_UPDATE_USERINFO = 'BEGIN_UPDATE_USERINFO';
export const SUCCESS_UPDATE_USERINFO = 'SUCCESS_UPDATE_USERINFO';
export const FAIL_UPDATE_USERINFO = 'FAIL_UPDATE_USERINFO';

// SET LOGOUT
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

// SET DETAIL PAGE COMMENT SECTION
export const BEGIN_COMMENT_REQUEST = 'BEGIN_COMMENT_REQUEST';
export const SUCCESS_COMMENT_REQUEST = 'SUCCESS_COMMENT_REQUEST';
export const FAIL_COMMENT_REQUEST = 'FAIL_COMMENT_REQUEST';
export const SET_COMMENTS_LIST = 'SET_COMMENTS_LIST';

// SET FEEDER
export const BEGIN_PRODUCTS_FEED = 'BEGIN_PRODUCTS_FEED';
export const SUCCESS_PRODUCTS_FEED = 'SUCCESS_PRODUCTS_FEED';
export const FAIL_PRODUCTS_FEED = 'FAIL_PRODUCTS_FEED';

// SET COMPARE ITEMS
// export const Compare_ITEM_ADD = 'Compare_ITEM_ADD';
// export const Compare_ITEM_REMOVE = 'Compare_ITEM_REMOVE';